spring.application.name=msvc-cursos
server.port=8002

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/msvc_cursos?sslmode=disable
spring.datasource.username=johandev
spring.datasource.password=Tropelias.1.1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true